name: 部署化简到生产服务器上
on:
  #监听push操作
  pull_request:
    branches:
      # main分支，你也可以改成其他分支
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install -g pnpm
        run: npm install -g pnpm
      - name: pnpm install
        run: pnpm install
      - name: npm run build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: export NODE_OPTIONS="--max_old_space_size=4096" && npm run build
      # 命名这个任务为发布Deploy
      - name: Deploy
        # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: 'ssh scp ssh pipelines'
          LASTSSH: 'Doing something after copying'
        with:
          host: ${{ secrets.USER_HOST }}
          user: ${{ secrets.USER_NAME }}
          pass: ${{ secrets.USER_PASS }}
          connect_timeout: 10s
          local: './dist/*'
          remote: /www/wwwroot/huajian.smallpig.site/main/dist
